extends Node
class_name CursorManager 

@onready var default_cursor : Resource = preload("res://resources/cursors/pointer_a.png")
@onready var place_cursor : Resource = preload("res://resources/cursors/target_round_b.png")
@onready var edit_cursor : Resource = preload("res://resources/cursors/message_dots_round.png")
@onready var hand_cursor : Resource = preload("res://resources/cursors/hand_open.png")

func reset_cursor() -> void:
	Input.set_custom_mouse_cursor(default_cursor, Input.CURSOR_ARROW, Vector2(8, 8))

func place() -> void:
	Input.set_custom_mouse_cursor(place_cursor, Input.CURSOR_ARROW, Vector2(32, 32))

func edit() -> void:
	Input.set_custom_mouse_cursor(edit_cursor, Input.CURSOR_ARROW, Vector2(32, 32))

func hand() -> void:
	Input.set_custom_mouse_cursor(hand_cursor, Input.CURSOR_ARROW, Vector2(32, 32))